name: Release Chart

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if Chart file has changed
        id: chartchanges
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'Chart.yaml'

      - name: Set Default
        if: steps.chartchanges.outputs.src == 'true'
        id: default
        run: echo "default=default" >> $GITHUB_ENV

      - name: Set Rev
        if: steps.chartchanges.outputs.src == 'false'
        id: default
        run: echo "default=rev" >> $GITHUB_ENV

      - name: Print Default
        run: |
          echo "Default is ${{ steps.default.outputs.default }}"